#lang racket

;a.
;(sine 12.15)
;(p (sine 4.05))
;(p (p (sine 1.35)))
;(p (p (p (sine 0.45))))
;(p (p (p (p (sine 0.15)))))
;(p (p (p (p (p sine 0.05)))))
;(p (p (p (p (p 0.05)))))

;procedure p applied 5 times

;b. order of growth generated by process is logarithmic (both in space and # of steps) b/c we divide a by 3 at each step